Downstream hostupdatepolicy test
openshift/baremetal-operator pull request #380
Opened 2024-10-10 03:35 UTC by rhjanders

2024-10-11 14:48 UTC, dtantsur commented on controllers/metal3.io/baremetalhost_controller.go
> +		hfsDirty, hfs, err := r.getHostFirmwareSettings(info)
I have a wild guess that Go is being stupid here and creates a new locally scoped variable for hfsDirty. What if you do this instead:

```go
var hfs *metal3api.HostFirmwareSettings
hfsDirty, hfs, err = r.getHostFirmwareSettings(info)
```

Important: use `=` not `:=`!!!

2024-10-14 21:13 UTC, iurygregory requested changes

2024-10-14 21:13 UTC, iurygregory commented on pkg/provisioner/provisioner.go
> +	// TargetFirmwareComponents []metal3api.FirmwareUpdate
You need to have this available since it will be used for the firmware updates

2024-10-14 21:13 UTC, iurygregory commented on pkg/provisioner/ironic/servicing.go
> +	// TODO: Add service steps for firmware updates
We don't have the logic for the firmware updates  here, so we won't do any action at all.
You can get some inspiration on  https://github.com/metal3-io/baremetal-operator/blob/main/pkg/provisioner/ironic/ironic.go#L1250-L1277

2024-10-14 21:13 UTC, iurygregory commented on controllers/metal3.io/baremetalhost_controller.go
> +	if servicingData.LiveFirmwareUpdateAllowed {
If I understood correctly `LiveFirmwareUpdateAllowed` will be related to the HFC, so you need to update things here to make it work, I've sent you a DM on Slack.

2024-10-14 21:13 UTC, iurygregory commented on controllers/metal3.io/baremetalhost_controller.go
> +	if provResult.ErrorMessage != "" {
In such case here you need to handle things for firmware updates,  see https://github.com/metal3-io/baremetal-operator/blob/main/controllers/metal3.io/baremetalhost_controller.go#L1171-L1174

2024-10-14 21:13 UTC, iurygregory commented on controllers/metal3.io/baremetalhost_controller.go
> +	if started && clearErrorWithStatus(info.host, metal3api.OperationalStatusServicing) {
Before this if started I would add the logic to handle the update for HFC information, for reference you can look at https://github.com/metal3-io/baremetal-operator/blob/main/controllers/metal3.io/baremetalhost_controller.go#L1178-L1190

2025-03-18 03:48 UTC, rhjanders commented
This work has been completed in other PRs and this one is no longer required.
/close

2025-03-18 03:48 UTC, closed without merging